apiVersion: extensions/v1
kind: deployment
metadata:
  name: 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: eureka-server
        env: prod
    spec:
      containers:
      - name: eureka-server
        image: 35.245.247.242:8082/eureka-server:latest
        imagePullPolicy: Always
      imagePullSecrets:
        - name: regsecret

apiVersion: v1
kind: Service
metadata:
  name: eureka-server 
  labels:
    service: eureka-server
spec:
  type: LoadBalancer
  ports:
  - port: 8761
    targetPort: 8761
    protocol: TCP
  selector:
    app: eureka-server
